package ru.zavodsvet.fgw_desktop_v2.common

const val AUTH_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/login/AuthView.fxml"
const val MAIN_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/MainView.fxml"
const val CHANGE_PASSWD_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/service/ChangePasswordView.fxml"
const val TEMPLATE_DATE_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/template/TemplateDateView.fxml"
const val TEMPLATE_DATE_TIME_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/template/TemplateDateTimeView.fxml"
const val ALL_OPERATION_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/AllOperationView.fxml"
const val VID_OPERATION_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/vidOper/VidOperationView.fxml"
const val KD_NAME_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/kdName/KDNameView.fxml"
const val PROD_PACK_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/prodPack/ProdPackView.fxml"
const val EMPLOYEE_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/employee/EmployeeView.fxml"
const val LOC_STORE_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/locStore/LocStoreView.fxml"
const val MANUFACTURING_PRODUCT_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/manufacturingProduct/ManufacturingProductView.fxml"
const val BALANCES_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/analitycs/balances/BalancesView.fxml"
const val TURNOVER_SHEET_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/analitycs/turnoverSheet/TurnoverSheetView.fxml"
const val DATE_TIME_DIALOG_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/DateTimeDialogView.fxml"
const val CARD_OPERATION_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/cardOper/CardOperationView.fxml"
const val BIND_PERMIT_DIALOG_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/cardOper/BindPermitDialogView.fxml"
const val CARD_SPECIFICATION_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/cardOper/cardSpecOper/CardSpecificationView.fxml"
const val DIRECT_DIALOG_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/allOperation/cardOper/cardSpecOper/DirectDialogView.fxml"
const val CARD_PROD_PACK_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/prodPack/cardProdPack/CardProdPackView.fxml"
const val CARD_LOC_STORE_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/locStore/cardLocStore/CardLocStoreView.fxml"
const val TICKET_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/manufacturingProduct/TicketView.fxml"
const val QUANTITY_SUB_LOC_STORE_DIALOG_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/handbook/locStore/cardLocStore/QuantitySubLocStoreDialogView.fxml"
const val CARD_SP_TEST_REPORT_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/testReport/cardTestReport/cardSpTestReport/CardSpTestReportView.fxml"
const val CARD_TEST_REPORT_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/testReport/cardTestReport/CardTestReportView.fxml"
const val TEST_REPORT_VIEW = "/ru/zavodsvet/fgw_desktop_v2/view/controller/menuBar/operation/testReport/TestReportView.fxml"
